### ISSUE TITLE
No longer builds

### ISSUE THREAD

**Issue by alexxroche** [glebpom/rust-ifstructs#3]
I was trying to compile [rust-dhcp](https://github.com/lancastr/rust-dhcp)
and it seems to be tangled in a mess of old dependencies. I tried to download rust-netif by hand and compile it but:
```shell

git clone git@github.com:glebpom/rust-netif.git
cd rust-netif
cargo build```
error: failed to read `rust-netif/ipconfig/Cargo.toml`

Caused by:
  No such file or directory (os error 2)

rust-netif depends on ifcontrol but doesn't know how to fetch it.

I'm using:
rustc 1.46.0-nightly (16957bd4d 2020-06-30)
cargo 1.46.0-nightly (c26576f9a 2020-06-23)

**Comment by glebpom** [comment]
Thanks for your interest. I've remove the outdated dependency from the workspace settings.

**Comment by alexxroche** [comment]
Now compiles. (Thank you.)
